//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Endereco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Endereco()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int idEndereco { get; set; }
        public int idCliente { get; set; }

        [Requerid]
        [Display(Name = "Apelido do Endereço")]
        public string nomeEndereco { get; set; }

        [Requerid]
        [Display(Name = "Endereço")]
        public string logradouroEndereco { get; set; }

        [Display(Name = "Complemento")]
        public string complementoEndereco { get; set; }

        [Requerid]
        [Display(Name = "Numero")]        
        public string numeroEndereco { get; set; }

        [Requerid]
        [Display(Name = "CEP")]
        public string CEPEndereco { get; set; }
        
        [Requerid]
        [Display(Name = "Cidade")]
        public string cidadeEndereco { get; set; }

        public string paisEndereco { get; set; }
        public string UFEndereco { get; set; }
    
        public virtual ClienteViewModel Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
